# Generated by Django 5.1.1 on 2024-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreated']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='text_color',
            new_name='textColor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_cover',
        ),
        migrations.AddField(
            model_name='post',
            name='photoCover',
            field=models.ImageField(default='default.png', upload_to='post-covers/'),
        ),
    ]
